name: Java CI with Maven and Docker in MacOS

on:
   push:
   pull_request:
   
jobs:
   build:
      runs-on: macos-13
      
      name: Build in macOS
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
           java-version: 8
           distribution: 'temurin'
      - name: Install Docker
        uses: docker/setup-docker-action@v4.1.0
        with:
           set-host: true
      - name: Build with Maven
        run: mvn verify -Pdocker
        working-directory: hellodocker